name: ninexmano_matrix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_database: ^11.0.4
  vibration: ^3.1.4
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
